language: php

php:
  - 7.2

services:
  - mysql
  
before_script:
  - mysql -u root -e 'CREATE DATABASE postings;'
  - mysql -u root postings < soen341/mysql.txt
  - mysql -u root postings < soen341/webpages/EmployersBACK_update_postings.php

script:
  - vendor/bin/phpunit soen341/testing/EmployerCandidateSelectionTest.php
  - vendor/bin/phpunit soen341/testing/LoginTest.php
  - vendor/bin/phpunit soen341/testing/SearchTest.php
  - vendor/bin/phpunit soen341/testing/SignupTest.php
  - vendor/bin/phpunit soen341/testing/StudentApplicationTest.php
  - vendor/bin/phpunit soen341/testing/UpdatePostingTest.php
  - vendor/bin/phpunit soen341/testing/UpdateProfileTest.php
  
  
