language: php

php:
  - 7.2

services:
  - mysql
  
before_script:
  - mysql -u root -e 'CREATE DATABASE postings;'
  - mysql -u root postings < $TRAVIS_BUILD_DIR/soen341/mysql.txt
  - mysql -u root postings < $TRAVIS_BUILD_DIR/soen341/BACK_update_postings.php

script:
  - phpunit $TRAVIS_BUILD_DIR/soen341/testing/SignUpTest.php
  - phpunit $TRAVIS_BUILD_DIR/soen341/testing/LoginTest.php
  - phpunit $TRAVIS_BUILD_DIR/soen341/testing/UpdateProfileTest.php
  - phpunit $TRAVIS_BUILD_DIR/soen341/testing/UpdatePostingTest.php
  - phpunit $TRAVIS_BUILD_DIR/soen341/testing/SearchTest.php
  
